server:
  port: 9002

spring:
  datasource:
    url: jdbc:h2:mem:test-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    #properties:
    #  hibernate:
    #  format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/smh-club
          jwk-set-uri: http://localhost:8080/realms/smh-club/protocol/openid-connect/certs
