## Externalized version of application.yml for production.
server:
  port: ${CLUB_HATEOAS_API_PORT}

  ssl:
    bundle: server
    enabled-protocols: TLSv1.3

spring:
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: server
          keystore:
            location: classpath:keystore/smhclub.p12
            password: ${CLUB_REST_API_KEYSTORE_PWD}
            type: PKCS12

      pem:
        client:
          truststore:
            certificate: classpath:keystore/smhclub.cer

  datasource:
    url: ${CLUB_HATEOAS_API_DB_URL}
    username: ${CLUB_HATEOAS_API_DB_USER}
    password: ${CLUB_HATEOAS_API_DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${CLUB_HATEOAS_API_ISSUER_URI}
          jwk-set-uri: ${CLUB_HATEOAS_API_JWK_SET_URI}
