services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: ['start-dev', '--import-realm', '--verbose']
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
