## For use in production mode
server:
  port: ${CLUB_API_PORT}

## Data source configured either by the command line or via Env Vars
spring:
  datasource:
    url: ${CLUB_API_DB_URL}
    username: ${CLUB_API_DB_USER}
    password: ${CLUB_API_DB_PASSWORD}

## Disable swagger
springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false
