#Server configured through @Configuration and @Beans. Replaces in memory repos.
logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:h2:mem:dev-db;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  flyway:
    enabled: false
