server:
  port: 9000

logging:
  level:
    org.springframework.security: debug

spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 200

  jpa:
    open-in-view: false
